version: 2

models:
  - name: coingecko
    description: "Silver model for CoinGecko cryptocurrency market data. Reads raw data from S3 bronze layer and standardizes column names and types."
    columns:
      - name: coin_id
        description: "Unique identifier for the cryptocurrency (e.g., 'bitcoin', 'ethereum')"
        tests:
          - not_null
          - unique
      - name: coin_symbol
        description: "Cryptocurrency symbol (e.g., 'btc', 'eth')"
        tests:
          - not_null
      - name: coin_name
        description: "Full name of the cryptocurrency"
        tests:
          - not_null
      - name: price_usd
        description: "Current price in USD"
        tests:
          - not_null
      - name: market_cap_usd
        description: "Market capitalization in USD"
        tests:
          - not_null
      - name: market_cap_rank
        description: "Rank by market capitalization (1 = highest)"
        tests:
          - not_null
      - name: volume_24h_usd
        description: "24-hour trading volume in USD"
      - name: ingestion_date
        description: "Date when the data was ingested"
        tests:
          - not_null

  - name: defillama
    description: "Silver model for DeFiLlama protocol data. Reads raw data from S3 bronze layer and standardizes column names and types (TVL, changes, metadata)."
    columns:
      - name: protocol_id
        description: "Unique identifier for the DeFi protocol (may repeat across ingestions)"
        tests:
          - not_null
      - name: protocol_name
        description: "Protocol display name"
        tests:
          - not_null
      - name: protocol_slug
        description: "URL-friendly protocol identifier"
        tests:
          - not_null
      - name: protocol_category
        description: "Protocol category (e.g. CEX, Lending, DEX)"
      - name: tvl_usd
        description: "Total Value Locked in USD"
      - name: tvl_change_pct_1d
        description: "1-day TVL change percentage"
      - name: tvl_change_pct_7d
        description: "7-day TVL change percentage"
      - name: ingestion_date
        description: "Date when the data was ingested"
        tests:
          - not_null

  - name: yfinance
    description: "Silver model for Yahoo Finance stock market data. Reads raw data from S3 bronze layer and standardizes OHLCV column names and types."
    columns:
      - name: symbol
        description: "Stock or index symbol (e.g. AAPL, ^GSPC)"
        tests:
          - not_null
      - name: trade_date
        description: "Trading date"
        tests:
          - not_null
      - name: open_usd
        description: "Opening price in USD"
      - name: high_usd
        description: "High price in USD"
      - name: low_usd
        description: "Low price in USD"
      - name: close_usd
        description: "Closing price in USD"
        tests:
          - not_null
      - name: volume
        description: "Trading volume"
      - name: ingestion_date
        description: "Date when the data was ingested"
        tests:
          - not_null

  - name: crypto_prices
    description: "Gold model for cryptocurrency prices with enriched metrics and aggregations. Business-ready analytical data for BI and dashboards."
    columns:
      - name: coin_id
        description: "Unique identifier for the cryptocurrency"
        tests:
          - not_null
          - unique
      - name: coin_symbol
        description: "Cryptocurrency symbol"
        tests:
          - not_null
      - name: price_usd
        description: "Current price in USD"
        tests:
          - not_null
      - name: market_cap_rank
        description: "Rank by market capitalization"
        tests:
          - not_null
      - name: trend_7d
        description: "Price trend category based on 7-day change"
        tests:
          - not_null
          - accepted_values:
              values:
                [
                  "strong_uptrend",
                  "uptrend",
                  "sideways",
                  "downtrend",
                  "strong_downtrend",
                ]
      - name: market_cap_category
        description: "Market cap category (large_cap, mid_cap, small_cap, micro_cap)"
        tests:
          - not_null
          - accepted_values:
              values: ["large_cap", "mid_cap", "small_cap", "micro_cap"]
